allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  sqlite3: true
  vue-demi: true

ignoredBuiltDependencies:
  - better-sqlite3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sqlite3
  - vue-demi
